### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by orensaldanha** [abohannon/ticket-mailer#78]
## **Problem/Issue**
When I log in , it shows the user dashboard for a split second and then it goes back to the login page.

I do believe that this is because of the following error 

![capture](https://user-images.githubusercontent.com/36854536/38456299-d7bd42cc-3aa0-11e8-8da8-32bbad1dc96f.PNG)

**Comment by abohannon** [comment]
@orensaldanha can you double check your app settings for me? They should reflect the following preferences in the attached screenshots (I'll add this to the readme - my oversight, sorry!).

Make sure "Read access" is allowed for these items and also make sure "Allow this app to access your storefront data using the Storefront API" is checked at the bottom.

Let me know how this goes for you!

<img width="617" alt="screen shot 2018-04-07 at 10 41 55 am" src="https://user-images.githubusercontent.com/889536/38458216-96bf65de-3a50-11e8-8f4f-ac23c511af92.png">
<img width="988" alt="screen shot 2018-04-07 at 10 42 28 am" src="https://user-images.githubusercontent.com/889536/38458218-9896dba8-3a50-11e8-8599-0064e22431d9.png">

**Comment by orensaldanha** [comment]
Hi Adam,

I tried your fix but it still doesnt work..

Regards,
Oren



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by abohannon** [comment]
I looked back over your dev.js file. The values should be strings and not
arrays. Give that a shot and see if that fixes it.

**Comment by orensaldanha** [comment]
Hi Adam,

Yes it worked!

Thank you so much!

Regards,
Oren

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
